### ISSUE TITLE
Set raw private response to true

### ISSUE THREAD

**Issue by IloMuoto** [GraviDAO/lunar-assistant-bot#19]
Upon community request and vote, the default response when running the `lunar-view-roles` command should be set to **Private**

Within lunar-assistant-bot/blob/main/src/commands/lunar-view-roles.ts

Change line 29:
`const privateResponse = rawPrivateResponse ? rawPrivateResponse : false;`
to 
`const privateResponse = rawPrivateResponse ? rawPrivateResponse : true;`

**Comment by DRITConsulting** [comment]
With the proposed change, the case where rawPrivateResponse is false will incorrectly set privateResponse to true.

I suggest using the following line instead:
const privateResponse = (rawPrivateResponse || rawPrivateResponse == null)  ? true : false;

![image](https://user-images.githubusercontent.com/100054192/154826055-2357ec3d-e32e-4fbd-b61a-803128497afe.png)

**Comment by Ruborcalor** [comment]
Good catch @DRITConsulting !
